# PostgreSQL image
FROM postgres:14

# Set environment variables for the PostgreSQL database
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=diningdb

# Expose the PostgreSQL port
EXPOSE 5432
